// Venues that should never be persisted or returned by live retrieval.
// This mirrors public.venue_denylist in the database; keep both lists in sync.

export const DENIED_VENUES = [
  "Academic Radiology",
  "Acta odontológica latinoamericana",
  "Acta Tropica",
  "Advances in Atmospheric Sciences",
  "Advances in kidney disease and health",
  "Advances in Parasitology",
  "Aesthetic Plastic Surgery",
  "Animal Reproduction Science",
  "Annals of Emergency Medicine",
  "Annals of Hepatology",
  "Annals of Oncology",
  "Annals of Pharmacotherapy",
  "Annals of Physics",
  "Annals of the Rheumatic Diseases",
  "Annals of Vascular Surgery",
  "Anthropocene Science",
  "Antiviral Research",
  "Apidologie",
  "Appetite",
  "Applied Animal Behaviour Science",
  "Applied Geochemistry",
  "Applied Geomatics",
  "Applied Nursing Research",
  "Archives of gerontology and geriatrics",
  "Archives of gerontology and geriatrics (Print)",
  "Archives of Gynecology and Obstetrics",
  "Archives of Iranian medicine",
  "Archives of Medical Research",
  "Archives of Osteoporosis",
  "Archives of Physical Medicine and Rehabilitation",
  "Archivos de Bronconeumologia",
  "Asian Pacific Journal of Cancer Prevention",
  "Atmospheric research",
  "Autoimmunity Reviews",
  "Berghahn Books",
  "Best Practice & Research: Clinical Obstetrics & Gynaecology",
  "Best practice & research. Clinical gastroenterology",
  "BJOG: an International Journal of Obstetrics and Gynaecology",
  "BMC Public Health",
  "Bone Marrow Transplantation",
  "Breast Cancer Research and Treatment",
  "Burns",
  "Canadian family physician Medecin de famille canadien",
  "Canadian Journal of Cardiology",
  "Canadian Journal of Surgery",
  "Canadian oncology nursing journal = Revue canadienne de nursing oncologique",
  "Cancer Causes and Control",
  "Cancer Genetics",
  "Cancer Research",
  "Cancer Treatment Reviews",
  "Cell stress & chaperones",
  "Cell stress & chaperones (Print)",
  "Cerebellum",
  "Chapters in SUERF Studies",
  "Chemosphere",
  "Chest",
  "Clinical Epidemiology of Chronic Liver Diseases",
  "Clinical Lung Cancer",
  "Clinical medicine (London)",
  "Clinical Microbiology and Infection",
  "Clinical Research in Cardiology",
  "Clinical Rheumatology",
  "Coastal Engineering",
  "Current Hematologic Malignancy Reports",
  "Current HIV/AIDS Reports",
  "Current Infectious Disease Reports",
  "Endocrine Practice",
  "Enfermedades Infecciosas y Microbiologia Clinica",
  "Experimental Gerontology",
  "Eye",
  "Gaceta Sanitaria",
  "Haemophilia",
  "Heart and Vessels",
  "Heart, Lung and Circulation",
  "Immunologic research",
  "Indian Journal of Hematology and Blood Transfusion",
  "Indian Journal of Small Ruminants",
  "Infectious Disease Clinics of North America",
  "Injury",
  "Inquiry : a journal of medical care organization, provision and financing",
  "Intensive Care Medicine",
  "Internal and Emergency Medicine",
  "International Journal of Antimicrobial Agents",
  "International Journal of Cardiology",
  "International Journal of Nursing Education",
  "International Journal of Nursing Studies",
  "International Journal of Obesity",
  "International Journal of Oral & Maxillofacial Surgery",
  "International Journal of Pediatric Otorhinolaryngology",
  "ISPRS Journal of Photogrammetry and Remote Sensing",
  "Joint, bone, spine : revue du rhumatisme",
  "Jornal de Pediatria",
  "Journal of Allergy and Clinical Immunology",
  "Journal of Bodywork and Movement Therapies",
  "Journal of Cancer Education",
  "Journal of cancer survivorship",
  "Journal of Cardiac Failure",
  "Journal of Cardiovascular Translational Research",
  "Journal of Clinical Epidemiology",
  "Journal of Clinical Immunology",
  "Journal of clinical sleep medicine : JCSM : official publication of the American Academy of Sleep Medicine",
  "Journal of Clinical Outcomes Management",
  "Journal of Clinical Virology",
  "Journal of Cystic Fibrosis",
  "Journal of Ethnopharmacology",
  "Journal of Fluorescence",
  "Journal of healthcare protection management : publication of the International Association for Hospital Security",
  "Journal of Hepatology",
  "Journal of Hydro-environment Research",
  "Journal of Hydrology",
  "Journal of medical systems",
  "Journal of Modern Jewish Studies",
  "Journal of Neuroimmunology",
  "Journal of Neurological Sciences",
  "Journal of Obstetric, Gynecologic and Neonatal Nursing",
  "Journal of Obstetrics and Gynaecology Canada",
  "Journal of Pain and Symptom Management",
  "Journal of The Lepidopterists Society",
  "Journal of the National Medical Association",
  "Journal of the Pediatric Infectious Diseases Society",
  "Journal of Thoracic Oncology",
  "Journal of Trace Elements in Medicine and Biology",
  "Kidney International",
  "Lancet Infectious Diseases",
  "Lancet Neurology",
  "Lancet. Infectious Diseases (Print)",
  "Lung Cancer",
  "Nurse Education Today",
  "Nursing Education Perspectives",
  "Nursing History Review",
  "Nursing Science Quarterly",
  "Ophthalmology (Rochester, Minn.)",
  "Osteoporosis International",
  "Pain Physician",
  "Palaeogeography, Palaeoclimatology, Palaeoecology",
  "Pakistan Journal of Commerce and Social Sciences",
  "Palliative Care and Social Practice",
  "Patient Education and Counseling",
  "Pediatric nephrology (Berlin, West)",
  "Pediatric Radiology",
  "Pediatric Research",
  "Pediatric surgery international (Print)",
  "Perioperative Care and Operating Room Management",
  "PharmacoEconomics (Auckland)",
  "Plant Ecology",
  "Preventive Medicine",
  "Preventive Veterinary Medicine",
  "Proceedings of the Social and Humaniora Research Symposium (SoRes 2018)",
  "Surgery",
  "Surgical Endoscopy",
  "Surveys in geophysics",
  "World journal of urology",
  "World Neurosurgery",
];

export function normalizeVenueKey(venue: unknown): string {
  return String(venue ?? "")
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "")
    .trim();
}

export const DENIED_VENUE_KEYS = new Set(
  DENIED_VENUES.map((venue) => normalizeVenueKey(venue)).filter(Boolean),
);

export function isDeniedVenue(venue: unknown): boolean {
  const key = normalizeVenueKey(venue);
  return key.length > 0 && DENIED_VENUE_KEYS.has(key);
}

// deno-lint-ignore no-explicit-any
export function filterDeniedVenuePapers<T extends Record<string, any>>(papers: T[]): T[] {
  return papers.filter((paper) => !isDeniedVenue(paper.venue));
}
