import React, { useMemo, useState } from 'react';
import { createPortal } from 'react-dom';
import { JelBibEntry, JelPaper, JelSection, Work } from '../types';
import { exportJelEvidenceTableAsCsv, exportJelPaperAsDocx } from '../services/exportService';
import { absBandLabel } from '../services/journalTiers';

// ---------------------------------------------------------------------------
// Progress label (in-progress drafting state)
// ---------------------------------------------------------------------------

/** "Drafting sections… X of N complete" where X never exceeds N.
 *  N is the outline length + 1 (the appended "Critical Assessment" section),
 *  but the pipeline can persist more sections than a stale/confirmed outline
 *  predicted — so we take max(expected, drafted) to avoid the impossible
 *  "8 of 7". With no outline yet, show the raw count without a fraction. */
function draftProgressLabel(paper: JelPaper): string {
  const drafted = paper.sections?.length ?? 0;
  const outlineLen = paper.outline?.sections?.length ?? 0;
  if (!outlineLen) return `Drafting sections… ${drafted} so far`;
  const total = Math.max(outlineLen + 1, drafted); // +1 = appended Critical Assessment
  return `Drafting sections… ${drafted} of ${total} complete`;
}

// ---------------------------------------------------------------------------
// Export helpers
// ---------------------------------------------------------------------------

function buildPaperText(paper: JelPaper): string {
  const lines: string[] = [];
  const bibMap = new Map((paper.bibliography ?? []).map(e => [e.workId, e.number]));

  lines.push(paper.outline?.title ?? paper.query);
  lines.push(`Generated by Horizon Scanner — IADB Evidence Intelligence Platform`);
  lines.push(`Query: ${paper.query}`);
  lines.push(`Generated: ${paper.completedAt ? new Date(paper.completedAt).toLocaleString() : 'pending'}`);
  lines.push(`Words: ${paper.wordCount?.toLocaleString() ?? '—'} · Citations: ${paper.citationCount ?? '—'}`);
  lines.push('');

  if (paper.outline?.abstract) {
    lines.push('ABSTRACT');
    lines.push(paper.outline.abstract);
    lines.push('');
  }

  for (const section of paper.sections) {
    lines.push(`§${section.number}  ${section.heading}`);
    lines.push('');
    // Strip [workId] tokens — author-year text in prose is the citation
    const body = section.body.replace(/\s*\[[^\]]{3,}\]/g, '');
    lines.push(body);
    lines.push('');
  }

  if ((paper.bibliography ?? []).length > 0) {
    lines.push('EVIDENCE TABLE');
    lines.push('');
    for (const e of paper.bibliography) {
      const doi = e.doi ? ` https://doi.org/${e.doi}` : '';
      lines.push(`${e.number}. ${e.authors} (${e.year ?? 'n.d.'}). ${e.title}.${e.venue ? ` ${e.venue}.` : ''}${doi}${e.cited ? ' [cited]' : ''}${e.unverified ? ' [user-supplied, unverified]' : ''}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

function downloadText(content: string, filename: string) {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

// ---------------------------------------------------------------------------
// Status badge
// ---------------------------------------------------------------------------

function StatusBadge({ status }: { status: JelPaper['status'] }) {
  const map: Record<string, { label: string; className: string }> = {
    queued:  { label: 'Queued',  className: 'bg-slate-100 text-slate-600 border-slate-200' },
    running: { label: 'Drafting…', className: 'bg-amber-50 text-amber-700 border-amber-200 animate-pulse' },
    done:    { label: 'Ready',   className: 'bg-emerald-50 text-emerald-700 border-emerald-200' },
    error:   { label: 'Error',   className: 'bg-red-50 text-red-700 border-red-200' },
  };
  const { label, className } = map[status] ?? map.queued;
  return (
    <span className={`rounded-full px-2.5 py-0.5 text-[11px] font-semibold border ${className}`}>
      {label}
    </span>
  );
}

// ---------------------------------------------------------------------------
// Citation numbering — build workId → number map from bibliography
// ---------------------------------------------------------------------------

function buildCitationMap(bibliography: JelBibEntry[]): Map<string, number> {
  const map = new Map<string, number>();
  for (const entry of bibliography) {
    map.set(entry.workId, entry.number);
  }
  return map;
}

// ---------------------------------------------------------------------------
// Section renderer — JEL author-year style
//
// Qwen writes "Author (year) [workId] find that..."
// [workId] tokens are stripped from display — the author-year text is the
// citation. The bibliography at the bottom provides full references.
// ---------------------------------------------------------------------------

function SectionBody({ body, citationMap: _citationMap }: { body: string; citationMap: Map<string, number> }) {
  // Strip all [workId] tokens; keep everything else as-is
  const cleaned = body.replace(/\s*\[[^\]]{3,}\]/g, '');
  return (
    <div className="text-[14px] text-slate-800 leading-relaxed whitespace-pre-wrap font-serif">
      {cleaned}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Bibliography section
// ---------------------------------------------------------------------------

function Bibliography({ entries }: { entries: JelBibEntry[] }) {
  const [expanded, setExpanded] = useState(false);
  const VISIBLE = 15;
  const shown = expanded ? entries : entries.slice(0, VISIBLE);

  if (entries.length === 0) return null;

  const citedCount = entries.filter(e => e.cited).length;

  return (
    <section id="jel-section-bibliography" className="mb-10 scroll-mt-4">
      <h2 className="text-lg font-bold text-slate-900 mb-1 pb-2 border-b border-slate-100">
        Evidence Table
      </h2>
      <p className="text-[12px] text-slate-500 mb-4">
        All {entries.length} evidence papers, in the same order as the brief’s evidence table
        {citedCount > 0 && <> · {citedCount} cited in this paper</>}
      </p>
      <div className="space-y-2">
        {shown.map((e) => {
          const doiUrl = e.doi ? `https://doi.org/${e.doi}` : null;
          return (
            <div key={e.workId} className={`flex gap-3 text-[13px] leading-snug ${e.cited ? 'text-slate-700' : 'text-slate-400'}`}>
              <span className={`shrink-0 font-semibold tabular-nums w-7 text-right ${e.cited ? 'text-indigo-600' : 'text-slate-300'}`}>{e.number}.</span>
              <span>
                {e.authors} ({e.year ?? 'n.d.'}). {' '}
                {doiUrl ? (
                  <a href={doiUrl} target="_blank" rel="noopener noreferrer"
                    className="italic hover:text-indigo-700 hover:underline">
                    {e.title}
                  </a>
                ) : (
                  <span className="italic">{e.title}</span>
                )}
                {e.venue && <span className="text-slate-500"> — {e.venue}</span>}
                {e.cited && <span className="ml-1.5 rounded-full bg-indigo-50 border border-indigo-100 text-indigo-600 px-1.5 py-0.5 text-[10px] font-semibold align-middle">cited</span>}
                {e.unverified && <span className="ml-1.5 rounded-full bg-amber-50 border border-amber-200 text-amber-700 px-1.5 py-0.5 text-[10px] font-semibold align-middle">user-supplied · unverified</span>}
                {doiUrl && (
                  <a href={doiUrl} target="_blank" rel="noopener noreferrer"
                    className="ml-1 text-[11px] text-indigo-500 hover:underline">
                    ↗
                  </a>
                )}
              </span>
            </div>
          );
        })}
      </div>
      {entries.length > VISIBLE && (
        <button
          onClick={() => setExpanded(v => !v)}
          className="mt-3 text-xs font-semibold text-teal-600 hover:text-teal-800 transition"
        >
          {expanded ? `Collapse` : `Show all ${entries.length} papers`}
        </button>
      )}
    </section>
  );
}

// ---------------------------------------------------------------------------
// Table of contents
// ---------------------------------------------------------------------------

function TableOfContents({
  sections,
  activeNumber,
  onSelect,
}: {
  sections: JelSection[];
  activeNumber: string | null;
  onSelect: (n: string) => void;
}) {
  return (
    <nav className="space-y-0.5">
      {sections.map((s) => (
        <button
          key={s.number}
          onClick={() => onSelect(s.number)}
          className={`w-full text-left px-3 py-1.5 rounded-lg text-xs transition ${
            activeNumber === s.number
              ? 'bg-indigo-50 text-indigo-700 font-semibold'
              : 'text-slate-600 hover:bg-slate-50 hover:text-slate-900'
          }`}
        >
          <span className="text-slate-400 mr-1.5 tabular-nums">§{s.number}</span>
          {s.heading}
          {s.wordCount > 0 && (
            <span className="ml-1.5 text-slate-300 text-[10px]">{s.wordCount.toLocaleString()}w</span>
          )}
        </button>
      ))}
    </nav>
  );
}

// ---------------------------------------------------------------------------
// Main component
// ---------------------------------------------------------------------------

interface JelPaperViewProps {
  paper: JelPaper;
  onClose: () => void;
  onRefresh?: () => void;
  onRevise?: (instruction: string) => Promise<void>;
  // Lazily fetch the corpus Work rows for this paper's bibliography (used by the
  // "Evidence table (CSV)" export). Absent → export degrades to bib fields only.
  onLoadEvidenceWorks?: () => Promise<Work[]>;
}

export default function JelPaperView({ paper, onClose, onRefresh, onRevise, onLoadEvidenceWorks }: JelPaperViewProps) {
  const [activeSectionNumber, setActiveSectionNumber] = useState<string | null>(
    paper.sections[0]?.number ?? null,
  );
  const [toast, setToast] = useState<string | null>(null);
  const [downloadMenuOpen, setDownloadMenuOpen] = useState(false);
  const [mobileTocOpen, setMobileTocOpen] = useState(false);
  const [reviseOpen, setReviseOpen] = useState(false);
  const [reviseText, setReviseText] = useState('');
  const [reviseSubmitting, setReviseSubmitting] = useState(false);
  const [reviseError, setReviseError] = useState<string | null>(null);

  const title = paper.outline?.title ?? paper.query;
  const abstract = paper.outline?.abstract ?? null;

  // Build citation number map from bibliography (workId → [N])
  const citationMap = useMemo(
    () => buildCitationMap(paper.bibliography ?? []),
    [paper.bibliography],
  );

  function showToast(msg: string) {
    setToast(msg);
    setTimeout(() => setToast(null), 2000);
  }

  async function handleCopy() {
    const text = buildPaperText(paper);
    await navigator.clipboard.writeText(text);
    showToast('Paper copied to clipboard');
  }

  function handleDownloadTxt() {
    setDownloadMenuOpen(false);
    const text = buildPaperText(paper);
    const safe = (paper.outline?.title ?? paper.query)
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .slice(0, 50);
    downloadText(text, `jel-paper-${safe}.txt`);
    showToast('Downloading…');
  }

  const [docxExporting, setDocxExporting] = useState(false);
  async function handleDownloadDocx() {
    setDownloadMenuOpen(false);
    if (docxExporting) return;
    setDocxExporting(true);
    try {
      // Rich evidence-table attributes (SMS, methodology, region) live on the
      // corpus Work rows. Use embedded evidenceWorks if present; otherwise lazily
      // fetch them so a Library-opened paper still exports a full table.
      let works = paper.evidenceWorks;
      if ((!works || works.length === 0) && onLoadEvidenceWorks) {
        showToast('Preparing Word document…');
        try { works = await onLoadEvidenceWorks(); } catch { /* degrade to bib fields */ }
      }
      await exportJelPaperAsDocx(paper, works);
      showToast('Downloaded Word document');
    } catch {
      // Degrade gracefully — export with whatever bibliography fields we have.
      await exportJelPaperAsDocx(paper, paper.evidenceWorks);
      showToast('Downloaded (limited attributes)');
    } finally {
      setDocxExporting(false);
    }
  }

  const [evExporting, setEvExporting] = useState(false);
  async function handleExportEvidenceTable() {
    if (evExporting) return;
    setEvExporting(true);
    try {
      // Rich attributes (SMS, methodology, region, citations) live on the corpus
      // Work rows, not on the bibliography. Use embedded evidenceWorks if present;
      // otherwise lazily fetch them so a Library-opened paper still exports fully.
      let works = paper.evidenceWorks;
      if ((!works || works.length === 0) && onLoadEvidenceWorks) {
        showToast('Preparing evidence table…');
        works = await onLoadEvidenceWorks();
      }
      exportJelEvidenceTableAsCsv(paper, works);
      showToast('Evidence table exported');
    } catch {
      // Degrade gracefully — export with whatever bibliography fields we have.
      exportJelEvidenceTableAsCsv(paper, paper.evidenceWorks);
      showToast('Exported (limited attributes)');
    } finally {
      setEvExporting(false);
    }
  }

  function scrollToSection(number: string) {
    setActiveSectionNumber(number);
    document.getElementById(`jel-section-${number}`)?.scrollIntoView({
      behavior: 'smooth',
      block: 'start',
    });
  }

  const isInProgress = paper.status === 'queued' || paper.status === 'running';
  const revisionsLeft = 2 - (paper.regenerationsUsed ?? 0);

  async function submitRevise() {
    const txt = reviseText.trim();
    if (!txt || !onRevise) return;
    setReviseSubmitting(true);
    setReviseError(null);
    try {
      await onRevise(txt);
      setReviseOpen(false);
      setReviseText('');
      showToast('Revising…');
    } catch (e) {
      setReviseError(e instanceof Error ? e.message : 'Revision failed');
    } finally {
      setReviseSubmitting(false);
    }
  }

  return (
    <div className="fixed inset-0 bottom-14 md:bottom-0 z-[45] md:z-50 flex flex-col bg-white">
      {/* Header */}
      <header className="flex items-center justify-between gap-2 px-4 py-2.5 border-b border-slate-200 bg-white shrink-0">
        <div className="flex items-center gap-2 min-w-0">
          <button
            onClick={onClose}
            className="shrink-0 flex items-center gap-1 rounded-full px-3 py-1.5 text-slate-600 hover:text-slate-900 hover:bg-slate-100 transition font-semibold text-sm"
            title="Back to Library"
          >
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
              <polyline points="15 18 9 12 15 6" />
            </svg>
            <span>Back</span>
          </button>
          <div className="min-w-0">
            <div className="flex items-center gap-1.5">
              <span className="text-[10px] uppercase tracking-[0.15em] text-indigo-600 font-bold hidden sm:inline">JEL Survey Paper</span>
              <StatusBadge status={paper.status} />
              {isInProgress && onRefresh && (
                <button onClick={onRefresh} className="text-[10px] text-slate-500 hover:text-indigo-600 transition" title="Refresh">↻</button>
              )}
            </div>
            <h1 className="text-sm font-semibold text-slate-900 truncate mt-0.5">{title}</h1>
          </div>
        </div>
        <div className="flex items-center gap-1.5 shrink-0">
          {paper.status === 'done' && (
            <>
              <span className="text-[11px] text-slate-400 tabular-nums hidden sm:inline">
                {paper.wordCount?.toLocaleString() ?? '—'}w · {paper.citationCount ?? '—'} cit.
              </span>
              {onRevise && revisionsLeft > 0 && (
                <button onClick={() => setReviseOpen(true)} title={`${revisionsLeft} revision${revisionsLeft === 1 ? '' : 's'} left`} className="rounded-full border border-indigo-200 bg-indigo-50 px-2.5 py-1.5 text-xs font-medium text-indigo-700 hover:bg-indigo-100 transition">
                  Revise
                </button>
              )}
              <button onClick={handleCopy} className="rounded-full border border-slate-200 bg-white px-2.5 py-1.5 text-xs font-medium text-slate-700 hover:bg-slate-50 transition">
                Copy
              </button>
              <button
                onClick={() => void handleExportEvidenceTable()}
                disabled={evExporting}
                title="Export the evidence table as a CSV (with a cited / not-cited column)"
                className="rounded-full border border-slate-200 bg-white px-2.5 py-1.5 text-xs font-medium text-slate-700 hover:bg-slate-50 transition disabled:opacity-50"
              >
                {evExporting ? 'Exporting…' : 'Evidence table (CSV)'}
              </button>
              <div className="relative">
                <button
                  onClick={() => setDownloadMenuOpen(v => !v)}
                  disabled={docxExporting}
                  aria-haspopup="menu"
                  aria-expanded={downloadMenuOpen}
                  className="flex items-center gap-1 rounded-full bg-indigo-600 text-white px-2.5 py-1.5 text-xs font-semibold hover:bg-indigo-700 transition disabled:opacity-50"
                >
                  {docxExporting ? 'Exporting…' : 'Download'}
                  <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"><polyline points="6 9 12 15 18 9" /></svg>
                </button>
                {downloadMenuOpen && (
                  <>
                    <div className="fixed inset-0 z-[55]" onClick={() => setDownloadMenuOpen(false)} />
                    <div role="menu" className="absolute right-0 mt-1 z-[56] w-48 rounded-xl border border-slate-200 bg-white py-1 shadow-lg">
                      <button role="menuitem" onClick={() => void handleDownloadDocx()} className="w-full text-left px-3 py-2 text-xs text-slate-700 hover:bg-slate-50 transition">
                        Word document (.docx)
                      </button>
                      <button role="menuitem" onClick={handleDownloadTxt} className="w-full text-left px-3 py-2 text-xs text-slate-700 hover:bg-slate-50 transition">
                        Plain text (.txt)
                      </button>
                    </div>
                  </>
                )}
              </div>
            </>
          )}
        </div>
      </header>

      {reviseOpen && createPortal(
        <div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/40 p-4" onClick={() => { if (!reviseSubmitting) setReviseOpen(false); }}>
          <div className="w-full max-w-lg rounded-2xl bg-white p-5 shadow-xl" onClick={(e) => e.stopPropagation()}>
            <h3 className="text-base font-bold text-slate-900">Revise the writing</h3>
            <p className="mt-1 text-xs text-slate-500">
              Rewrites the section(s) your instruction targets, over the paper's <strong>current evidence</strong> —
              tone, focus, length, emphasis. To change <em>which</em> papers are included, re-curate in Paper Studio.
            </p>
            <textarea
              value={reviseText}
              onChange={(e) => setReviseText(e.target.value)}
              rows={3}
              autoFocus
              placeholder="e.g. Tighten §3 and lead with the policy implication"
              className="mt-3 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-indigo-400 focus:outline-none"
            />
            <div className="mt-2 flex flex-wrap gap-1.5">
              {[
                'Be more cautious about causal claims',
                'Lead each section with the policy implication',
                'Emphasize the experimental (RCT/DiD) evidence we have',
                'Tighten the introduction',
              ].map((ex) => (
                <button key={ex} onClick={() => setReviseText(ex)} className="rounded-full border border-slate-200 bg-slate-50 px-2 py-0.5 text-[11px] text-slate-600 hover:bg-slate-100 transition">
                  {ex}
                </button>
              ))}
            </div>
            {reviseError && <p className="mt-2 text-xs text-red-600">{reviseError}</p>}
            <div className="mt-4 flex items-center justify-between">
              <span className="text-[11px] text-slate-400">{revisionsLeft} revision{revisionsLeft === 1 ? '' : 's'} left</span>
              <div className="flex gap-2">
                <button onClick={() => setReviseOpen(false)} disabled={reviseSubmitting} className="rounded-full px-3 py-1.5 text-xs font-medium text-slate-600 hover:bg-slate-100 disabled:opacity-50">
                  Cancel
                </button>
                <button onClick={() => void submitRevise()} disabled={reviseSubmitting || !reviseText.trim()} className="rounded-full bg-indigo-600 px-3 py-1.5 text-xs font-semibold text-white hover:bg-indigo-700 disabled:opacity-50">
                  {reviseSubmitting ? 'Starting…' : 'Revise draft'}
                </button>
              </div>
            </div>
          </div>
        </div>,
        document.body,
      )}

      {/* Body */}
      <div className="flex-1 flex overflow-hidden">
        {/* TOC sidebar — desktop only */}
        {paper.sections.length > 0 && (
          <aside className="hidden md:flex w-64 shrink-0 flex-col border-r border-slate-100 overflow-y-auto py-4 px-3">
            <div className="text-[10px] uppercase tracking-[0.15em] text-slate-400 font-bold mb-3 px-3">Contents</div>
            {abstract && (
              <button onClick={() => scrollToSection('abstract')} className={`w-full text-left px-3 py-1.5 rounded-lg text-xs transition mb-1 ${activeSectionNumber === 'abstract' ? 'bg-indigo-50 text-indigo-700 font-semibold' : 'text-slate-600 hover:bg-slate-50'}`}>Abstract</button>
            )}
            <TableOfContents
              sections={paper.sections.filter(s => String(s.number) !== 'critique')}
              activeNumber={activeSectionNumber}
              onSelect={scrollToSection}
            />
            {paper.sections.find(s => String(s.number) === 'critique') && (
              <button onClick={() => scrollToSection('critique')} className={`w-full text-left px-3 py-1.5 rounded-lg text-xs transition mt-1 ${activeSectionNumber === 'critique' ? 'bg-amber-50 text-amber-700 font-semibold' : 'text-amber-600 hover:bg-amber-50'}`}>⚖ Critical Assessment</button>
            )}
            {(paper.bibliography?.length ?? 0) > 0 && (
              <button onClick={() => scrollToSection('bibliography')} className={`w-full text-left px-3 py-1.5 rounded-lg text-xs transition mt-1 ${activeSectionNumber === 'bibliography' ? 'bg-indigo-50 text-indigo-700 font-semibold' : 'text-slate-600 hover:bg-slate-50'}`}>
                <span className="text-slate-400 mr-1.5">§</span>Evidence Table
                <span className="ml-1.5 text-slate-300 text-[10px]">{paper.bibliography.length}</span>
              </button>
            )}
          </aside>
        )}

        {/* Article body */}
        <main className="flex-1 overflow-y-auto px-4 py-4 md:px-12 md:py-8 max-w-4xl mx-auto">

          {/* Mobile TOC — collapsible, shown only on small screens */}
          {paper.sections.length > 0 && (
            <div className="md:hidden mb-4">
              <button
                onClick={() => setMobileTocOpen(v => !v)}
                className="w-full flex items-center justify-between rounded-xl border border-slate-200 bg-slate-50 px-4 py-2.5 text-sm font-semibold text-slate-700"
              >
                <span className="flex items-center gap-2">
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="8" y1="6" x2="21" y2="6" /><line x1="8" y1="12" x2="21" y2="12" /><line x1="8" y1="18" x2="21" y2="18" /><line x1="3" y1="6" x2="3.01" y2="6" /><line x1="3" y1="12" x2="3.01" y2="12" /><line x1="3" y1="18" x2="3.01" y2="18" /></svg>
                  Contents ({paper.sections.length} sections)
                </span>
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" className={`transition-transform ${mobileTocOpen ? 'rotate-180' : ''}`}>
                  <polyline points="6 9 12 15 18 9" />
                </svg>
              </button>
              {mobileTocOpen && (
                <div className="mt-1 rounded-xl border border-slate-200 bg-white p-3">
                  {abstract && (
                    <button onClick={() => { scrollToSection('abstract'); setMobileTocOpen(false); }} className="w-full text-left px-3 py-2 rounded-lg text-xs text-slate-600 hover:bg-slate-50 transition mb-1">Abstract</button>
                  )}
                  <TableOfContents
                    sections={paper.sections.filter(s => String(s.number) !== 'critique')}
                    activeNumber={activeSectionNumber}
                    onSelect={(n) => { scrollToSection(n); setMobileTocOpen(false); }}
                  />
                  {(paper.bibliography?.length ?? 0) > 0 && (
                    <button onClick={() => { scrollToSection('bibliography'); setMobileTocOpen(false); }} className="w-full text-left px-3 py-2 rounded-lg text-xs text-slate-600 hover:bg-slate-50 transition mt-1">Evidence Table ({paper.bibliography.length})</button>
                  )}
                </div>
              )}
            </div>
          )}
          {/* In-progress state */}
          {isInProgress && (
            <div className="rounded-xl bg-amber-50 border border-amber-200 px-5 py-4 mb-6 flex items-start gap-3">
              <div className="w-4 h-4 rounded-full border-2 border-amber-500 border-t-transparent animate-spin shrink-0 mt-0.5" />
              <div>
                <div className="text-sm font-semibold text-amber-800">
                  {paper.status === 'queued' ? 'Paper queued — starting shortly…' : draftProgressLabel(paper)}
                </div>
                <div className="text-xs text-amber-700 mt-0.5">
                  This takes 3-8 minutes. You can close this view and check back via Library.
                </div>
              </div>
            </div>
          )}

          {/* Error state */}
          {paper.status === 'error' && (
            <div className="rounded-xl bg-red-50 border border-red-200 px-5 py-4 mb-6">
              <div className="text-sm font-semibold text-red-800">Generation failed</div>
              {paper.errorMessage && (
                <div className="text-xs text-red-700 mt-1 font-mono">{paper.errorMessage}</div>
              )}
            </div>
          )}

          {/* Title + abstract */}
          <div className="mb-6 md:mb-8">
            <h1 className="text-xl md:text-2xl font-bold text-slate-900 leading-tight mb-1">{title}</h1>
            <div className="text-xs text-slate-500">
              Horizon Scanner · IADB Evidence Intelligence Platform ·{' '}
              {paper.completedAt
                ? new Date(paper.completedAt).toLocaleDateString()
                : new Date(paper.createdAt).toLocaleDateString()}
            </div>
            {abstract && (
              <div id="jel-section-abstract" className="mt-5 rounded-xl bg-slate-50 border border-slate-200 px-5 py-4">
                <div className="text-[10px] uppercase tracking-[0.15em] text-slate-500 font-bold mb-2">Abstract</div>
                <p className="text-[14px] text-slate-700 leading-relaxed italic">{abstract}</p>
              </div>
            )}

            {/* Evidence provenance — which retrieval channels + filters produced
                the evidence set. Additive; absent on legacy papers. */}
            {(() => {
              const meta: any = paper.outline?.retrievalMetadata ?? {};
              // Query is always available on the paper itself, so the provenance
              // panel renders even for legacy papers without retrievalMetadata.
              const queryText = meta.query ?? paper.query ?? null;
              const CHANNEL_LABELS: Record<string, string> = {
                causal: 'Causal', recent: 'Recent', foundational: 'Foundational', lac: 'LAC-focused',
              };
              const channels = Array.isArray(meta.channels) ? meta.channels : [];
              const f = meta.filters ?? {};
              const filterChips: { label: string; value: string }[] = [];
              if (Array.isArray(f.regions) && f.regions.length) filterChips.push({ label: 'Region', value: f.regions.join(', ') });
              if (f.timePeriod) {
                const tp = f.timePeriod === 'custom' && (f.startDate || f.endDate)
                  ? `${f.startDate || '…'}–${f.endDate || 'now'}`
                  : f.timePeriod === 'recent' ? '2020+' : f.timePeriod === 'all' ? 'All years' : String(f.timePeriod);
                filterChips.push({ label: 'Time', value: tp });
              }
              // Scope chip only for legacy runs that explicitly narrowed/widened
              // (evidenceMatch direct/all). 'both'/unset → no chip (the breadth
              // classifier was removed 2026-06-17; new runs never set it).
              if (f.evidenceMatch === 'direct' || f.evidenceMatch === 'all') {
                filterChips.push({ label: 'Scope', value: f.evidenceMatch === 'direct' ? 'On-topic only' : 'All matches' });
              }
              // Sources = working-paper repos + institutional sources (the real SearchFilters fields)
              const srcs = [...(Array.isArray(f.workingPaperSources) ? f.workingPaperSources : []), ...(Array.isArray(f.institutionalSources) ? f.institutionalSources : [])];
              if (srcs.length) filterChips.push({ label: 'Sources', value: srcs.join(', ') });
              if (Array.isArray(f.journalTiers) && f.journalTiers.length) filterChips.push({ label: 'Journals', value: absBandLabel(f.journalTiers) });
              if (Array.isArray(f.publicationTypes) && f.publicationTypes.length) filterChips.push({ label: 'Doc types', value: f.publicationTypes.join(', ') });
              if (Array.isArray(f.methodology) && f.methodology.length) filterChips.push({ label: 'Methodology', value: f.methodology.join(', ') });
              if (!queryText && channels.length === 0 && filterChips.length === 0 && !meta.searchRunId) return null;
              return (
                <div className="mt-3 rounded-xl bg-indigo-50/60 border border-indigo-100 px-5 py-4">
                  <div className="text-[10px] uppercase tracking-[0.15em] text-indigo-600 font-bold mb-2.5">Evidence provenance</div>
                  {queryText && (
                    <div className="text-[12px] text-slate-700 mb-2.5 leading-snug">
                      <span className="text-slate-400">Query asked:</span> <span className="font-semibold">“{queryText}”</span>
                    </div>
                  )}
                  {channels.length > 0 ? (
                    <div className="flex flex-wrap items-center gap-1.5 mb-2">
                      <span className="text-[11px] text-slate-500 mr-0.5">Channels:</span>
                      {channels.map((c) => (
                        <span key={c} className="text-[10px] font-semibold px-2 py-0.5 rounded-full bg-white border border-indigo-200 text-indigo-700">
                          {CHANNEL_LABELS[c] ?? c}
                          {meta.channelCounts?.[c] != null && <span className="text-indigo-400 font-normal"> · {meta.channelCounts[c]}</span>}
                        </span>
                      ))}
                    </div>
                  ) : (
                    <div className="text-[11px] text-slate-500 mb-2">General corpus retrieval (no channel-specific surfacing recorded).</div>
                  )}
                  {filterChips.length > 0 && (
                    <div className="flex flex-wrap items-center gap-x-3 gap-y-1 text-[11px] text-slate-600">
                      {filterChips.map((chip) => (
                        <span key={chip.label}><span className="text-slate-400">{chip.label}:</span> {chip.value}</span>
                      ))}
                    </div>
                  )}
                  <div className="mt-2 text-[10px] text-slate-400">
                    {meta.evidenceCount != null && <>Built from {meta.evidenceCount} evidence paper{meta.evidenceCount !== 1 ? 's' : ''}. </>}
                    {paper.briefId && <>Generated from a saved evidence brief.</>}
                  </div>
                </div>
              );
            })()}
          </div>

          {/* Sections */}
          {paper.sections.map((section) => {
            const isCritique = String(section.number) === 'critique';
            return (
              <section
                key={section.number}
                id={`jel-section-${section.number}`}
                className="mb-10 scroll-mt-4"
              >
                {isCritique ? (
                  <div className="rounded-xl border border-amber-200 bg-amber-50 px-5 py-4">
                    <div className="flex items-center gap-2 mb-3">
                      <span className="text-amber-600 text-base">⚖</span>
                      <h2 className="text-base font-bold text-amber-900">{section.heading}</h2>
                    </div>
                    <div className="text-[11px] uppercase tracking-widest text-amber-500 font-bold mb-3">Devil's Advocate Assessment</div>
                    <SectionBody body={section.body} citationMap={citationMap} />
                    {section.citedWorkIds.length > 0 && (
                      <div className="mt-3 text-[11px] text-amber-400">
                        {section.citedWorkIds.length} citation{section.citedWorkIds.length !== 1 ? 's' : ''} · {section.wordCount.toLocaleString()} words
                      </div>
                    )}
                  </div>
                ) : (
                  <>
                    <h2 className="text-lg font-bold text-slate-900 mb-4 pb-2 border-b border-slate-100">
                      <span className="text-slate-400 mr-2">§{section.number}</span>
                      {section.heading}
                    </h2>
                    <SectionBody body={section.body} citationMap={citationMap} />
                    {section.citedWorkIds.length > 0 && (
                      <div className="mt-3 text-[11px] text-slate-400">
                        {section.citedWorkIds.length} citation{section.citedWorkIds.length !== 1 ? 's' : ''} · {section.wordCount.toLocaleString()} words
                      </div>
                    )}
                  </>
                )}
              </section>
            );
          })}

          {/* Editor QA — internal quality/audit reports (coherence, citation audit,
              citation integrity). Collapsed by default and clearly labelled "internal":
              this info is for the author to ACT ON, not part of the reader-facing paper. */}
          {(paper.outline?.correctorReport || paper.outline?.coherenceReport || paper.outline?.auditReport || paper.outline?.krisReport) && (
            <details className="mb-10 rounded-xl border border-slate-200 bg-white">
              <summary className="cursor-pointer select-none px-5 py-3 text-[11px] uppercase tracking-[0.15em] text-slate-500 font-bold">
                🔧 Editor QA · internal only — not part of the paper
              </summary>
              <div className="px-3 pb-3 space-y-1">

          {/* Corrector summary — what the single coordinated correction pass did */}
          {paper.outline?.correctorReport && (() => {
            const cr = paper.outline.correctorReport as any;
            const tot = (Object.values(cr.byType ?? {}) as any[]).reduce(
              (a: any, b: any) => ({ found: a.found + b.found, resolved: a.resolved + b.resolved }),
              { found: 0, resolved: 0 },
            );
            return (
              <div className="mb-3 rounded-lg bg-white border border-slate-200 px-3 py-2">
                <span className="text-[11px] uppercase tracking-widest text-slate-500 font-bold mr-2">Corrections applied</span>
                <span className="text-[11px] text-green-600">{tot.resolved} resolved</span>
                <span className="text-[11px] text-slate-400"> / {tot.found} found</span>
                {cr.remainingIssues?.length > 0 && <span className="text-[11px] text-amber-600 ml-2">⚠ {cr.remainingIssues.length} remaining</span>}
                <span className="text-[11px] text-slate-400 ml-2">· §{(cr.sectionsRewritten ?? []).join(", §") || "—"}</span>
              </div>
            );
          })()}

          {/* Coherence Report */}
          {paper.outline?.coherenceReport && (() => {
            const cr = paper.outline.coherenceReport as any;
            const issues: any[] = cr.issues ?? [];
            if (issues.length === 0) return null;
            return (
              <section className="mb-10 rounded-xl border border-blue-200 bg-blue-50 px-5 py-4">
                <div className="flex items-center gap-2 mb-3">
                  <span className="text-blue-600 text-base">◎</span>
                  <h2 className="text-base font-bold text-blue-900">Editorial Quality Notes</h2>
                </div>
                <p className="text-[13px] text-blue-700 mb-3 italic">{cr.overallAssessment}</p>
                <div className="space-y-2">
                  {issues.map((issue: any, i: number) => (
                    <div key={i} className="rounded-lg bg-white border border-blue-100 px-3 py-2">
                      <span className="text-[10px] uppercase tracking-widest font-bold text-blue-400 mr-2">{issue.type?.replace(/_/g, ' ')}</span>
                      <span className="text-[11px] text-slate-500">{issue.sections?.join(', ')}</span>
                      <p className="text-[12px] text-slate-700 mt-1">{issue.description}</p>
                      <p className="text-[12px] text-blue-600 mt-0.5">→ {issue.suggestion}</p>
                    </div>
                  ))}
                </div>
              </section>
            );
          })()}

          {/* Audit Report */}
          {paper.outline?.auditReport && (() => {
            const ar = paper.outline.auditReport as any;
            const s = ar.summary ?? {};
            const unsupported: any[] = (ar.claims ?? []).filter((c: any) => c.verdict === 'unsupported');
            return (
              <section className="mb-10 rounded-xl border border-slate-200 bg-slate-50 px-5 py-3">
                <div className="flex items-center gap-3 flex-wrap">
                  <span className="text-[11px] uppercase tracking-widest text-slate-500 font-bold">Citation Audit</span>
                  <span className="text-[11px] text-green-600">✓ {s.supported} supported</span>
                  <span className="text-[11px] text-yellow-600">~ {s.partial} partial</span>
                  {s.unsupported > 0 && <span className="text-[11px] text-red-600 font-semibold">✗ {s.unsupported} unsupported</span>}
                  <span className="text-[11px] text-slate-400">? {s.unverifiable} unverifiable</span>
                  <span className="text-[11px] text-slate-300">/ {ar.total} sampled</span>
                </div>
                {unsupported.length > 0 && (
                  <div className="mt-2 space-y-1">
                    {unsupported.map((c: any, i: number) => (
                      <div key={i} className="text-[11px] text-red-700 bg-red-50 rounded px-2 py-1">
                        <span className="font-mono text-[10px] text-red-400 mr-1">{c.workId}</span> {c.reason}
                      </div>
                    ))}
                  </div>
                )}
              </section>
            );
          })()}

          {/* Kris citation integrity report */}
          {paper.outline?.krisReport && (() => {
            const kr = paper.outline.krisReport as any;
            const hasIssues = (kr.mismatches?.length ?? 0) > 0;
            return (
              <section className="mb-6 rounded-xl border border-slate-200 bg-slate-50 px-5 py-3">
                <div className="flex items-center gap-3 flex-wrap">
                  <span className="text-[11px] uppercase tracking-widest text-slate-500 font-bold">Citation Integrity (Kris)</span>
                  <span className="text-[11px] text-green-600">✓ {kr.verified} verified</span>
                  {kr.notInOA > 0 && <span className="text-[11px] text-slate-400">◦ {kr.notInOA} not in OpenAlex (expected for working papers)</span>}
                  {hasIssues
                    ? <span className="text-[11px] text-amber-600 font-semibold">⚠ {kr.mismatches.length} title mismatch(es)</span>
                    : <span className="text-[11px] text-green-600">✓ no mismatches</span>}
                </div>
                {hasIssues && (
                  <div className="mt-2 space-y-1">
                    {kr.mismatches.map((m: any, i: number) => (
                      <div key={i} className="text-[11px] text-amber-800 bg-amber-50 rounded px-2 py-1">
                        <span className="font-mono text-[10px] text-amber-500 mr-1">{m.id?.slice(0,25)}</span>
                        <span className="text-slate-600">Local: "{m.localTitle}" — OA: "{m.oaTitle}"</span>
                      </div>
                    ))}
                  </div>
                )}
              </section>
            );
          })()}
              </div>
            </details>
          )}

          {/* Outline sections not yet drafted (in-progress) */}
          {isInProgress && paper.outline?.sections && (
            paper.outline.sections
              .filter((os) => !paper.sections.find((s) => s.number === os.number))
              .map((os) => (
                <section key={os.number} className="mb-10 opacity-40">
                  <h2 className="text-lg font-bold text-slate-400 mb-2">
                    <span className="mr-2">§{os.number}</span>
                    {os.heading}
                    <span className="ml-2 text-xs font-normal text-slate-400">drafting…</span>
                  </h2>
                  <div className="h-24 rounded-lg bg-slate-50 border border-dashed border-slate-200 animate-pulse" />
                </section>
              ))
          )}

          {/* Bibliography */}
          <Bibliography entries={paper.bibliography ?? []} />
        </main>
      </div>

      {/* Toast */}
      {toast && (
        <div className="fixed bottom-6 left-1/2 -translate-x-1/2 rounded-full bg-slate-900 text-white text-xs px-4 py-2 shadow-lg pointer-events-none z-50">
          {toast}
        </div>
      )}
    </div>
  );
}
